# Generated by Django 6.0.2 on 2026-04-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women')], max_length=10),
        ),
    ]
